### ISSUE TITLE
部分样式问题

### ISSUE THREAD

**Issue by zxhycxq** [KieSun/Chat-Buy-React#11]
1、聊天界面，文字过长的话，右侧的头像会扁
![image](https://user-images.githubusercontent.com/11674203/34506313-93ca2f64-f066-11e7-8589-ccb302c3ad69.png)

2、好像是对方联系还是订单页面点击返回之后的报错。

`TypeError：无法读取未定义的属性'get'
Chat.componentWillUnmount
d：/Demo/react-demo/Chat-Buy-React/chat-buy-react/src/container/chat.jsx：50`

上传了好几次图片都没有成功，只好放文字了。

**Comment by KieSun** [comment]
好的 问题已知晓
