### ISSUE TITLE
MongoDB connect failed

### ISSUE THREAD

**Issue by seasonscao** [KieSun/Chat-Buy-React#13]
按步骤安装了 MongoDB，连接失败。是因为我这个端口被占用了吗？请指教一下，谢谢。

![jietu20180104-162054](https://user-images.githubusercontent.com/16096229/34555230-9f0f49d0-f16b-11e7-8fcd-f8ba6e49d245.jpg)

**Comment by jianfenkezhan** [comment]
执行下下面的命令， 然后在mongo试试。
$ mongod

**Comment by jianfenkezhan** [comment]
执行以下命令：
```bash
$ mongod
```

**Comment by seasonscao** [comment]
提示这个：

[cid:7B6408B4-A2FD-4A93-8545-E9F8AA6839D0]



On 4 Jan 2018, at 16:33, 穆建国 <notifications@github.com<mailto:notifications@github.com>> wrote:


执行以下命令：

$ mongod

**Comment by seasonscao** [comment]
提示这个：

<img width="570" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/16096229/34555715-3510a94a-f16e-11e7-96d4-1370714b4bd9.png">

**Comment by jianfenkezhan** [comment]
```bash
 cd /
 sudo mkdir /data
 sudo touch /data/log/mongod.log
 sudo mkdir /data/db

 cd /ect
 sudo vi mongod.conf

 写入下面的内容

-----
dbpath=/data/db
logpath=/data/log/mongod.log
logappend=true
port=27017
-----
保存后运行下面

 sudo chmod 777 /data
 mongod --config /etc/mongod.conf
 mongo

 ```

**Comment by Min-field** [comment]
![image](https://user-images.githubusercontent.com/19371642/34658468-4d06493e-f46a-11e7-907a-28142c056e54.png)
你把这里把mongod服务关了 再去执行mongo命令，肯定连不上啊
你可以在 mongod --config /usr/local/etc/mongod.conf 命令之后新开一个terminal tab 开到项目目录敲mongo 命令 或者
```
   mongod --config /usr/local/etc/mongod.conf& // 使用&将服务挂到后台
   mongo
```
