### ISSUE TITLE
infinite loading on windows 

### ISSUE THREAD

**Issue by francishero** [KieSun/Chat-Buy-React#2]
![bug](https://user-images.githubusercontent.com/16598693/34472489-7f08ab54-ef18-11e7-8dc9-7dc930c387ac.PNG)
after starting server and client there is an just loading, user cant click anything

**Comment by KieSun** [comment]
I'll see the problem now

**Comment by KieSun** [comment]
Sorry, I did not reproduce the problem. You did not input anything and click the login button?
