### ISSUE TITLE
Project registration meets problems

### ISSUE THREAD

**Issue by dragonnahs** [KieSun/Chat-Buy-React#3]
when I register i meet an error, it seems to be a problem with proxyable. I just modify port.
`Proxy error: Could not proxy request /user/register from localhost:3000 to http://localhost:27017/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).`

**Comment by KieSun** [comment]
If you want listen port 27017. You need modify server.js code 
```js
server.listen(27017, function() {
  console.log("Node app start at port 27017");
});
```
and package.json
```json
"proxy": "http://localhost:27017"
```

**Comment by webLeeSun** [comment]
您好，打扰了，我也遇到了相同的问题，尝试修改了您说的这两个文件的端口号，在做登录请求的时候，也同样会提示这个错误。不知道是否是我其他地方使用有误？
`"proxy": "http://localhost:27017"`
`server.listen(27017, function() {
  console.log("Node app start at port 27017");
});`

**Comment by KieSun** [comment]
@webLeeSun 请提供报错信息
