### ISSUE TITLE
安装nodemon报错

### ISSUE THREAD

**Issue by notCoolBean** [KieSun/Chat-Buy-React#4]
![image](https://user-images.githubusercontent.com/26993086/34473145-e89c01d8-efa9-11e7-9a47-48e3e3024246.png)
我找了 在这个路径下面有这个文件不过查看这个文件之后是一个链接文件
![image](https://user-images.githubusercontent.com/26993086/34473160-232b1adc-efaa-11e7-9250-9cf28ba6c163.png)
怎么解决 卡在这里了

**Comment by KieSun** [comment]
如何安装失败，使用 cnpm 安装，下次还有报错请截图截全
