### ISSUE TITLE
npm run start   error

### ISSUE THREAD

**Issue by mowatermelon** [KieSun/Chat-Buy-React#6]
![image](https://user-images.githubusercontent.com/18508817/34476998-cd086d72-efd0-11e7-91c2-df6c73fe26a8.png)

执行`npm run start`之后，提示一个不可忽视的`遇见一个意外标记`，地址指向是`src/index.js`中`16`行的`<AppContainer>`，

**Comment by KieSun** [comment]
重新拉个代码

**Comment by mowatermelon** [comment]
@KieSun   
> 我试过不修改`package.json` ,然后直接执行`start`页面是正常出来的，但是请求服务失败，所以需要先启动后台服务，但是启动服务的时候，遇到一些问题，目前是通过修改`package.json`才能正常执行，可是修改之后，`start`就报错了。

- 首先执行`npm run server`的时候，报错。

![image](https://user-images.githubusercontent.com/18508817/34477300-062b2c86-efd4-11e7-9763-a12a284be646.png)

- 删除前面的`NODE_ENV`和`BABEL_ENV`变量的赋值，修改了`package.json`中`babel`属性内容，还是报错，说必须要对这两个变量赋值。

```json
"presets": [
      "react-app",
      [
        "env",
        {
          "targets": {
            "node": true
          },
          "NODE_ENV":"development",
          "BABEL_ENV":"development"
        }
      ]
    ]
```

- 所以我在项目根文件中添加了`.babelrc`文件，并添加了如下内容。
```json
{
  "presets": [
    ["env",
      {  
        "NODE_ENV":"development",
        "BABEL_ENV":"development"
      }
    ]
  ]
}

```

- 并将原有内容都还原，仅修改`start`对应的指令。
```json
"server": "nodemon --exec babel-node server/server.js",
```

- 这样我的 `server`才执行成功，但是`start`就执行不成功了，报了如上的错误。

**Comment by KieSun** [comment]
因为你 env 是不能解析 JSX 的

**Comment by mowatermelon** [comment]
我现在将`.babelrc`文件中内容修改为以下内容，然后执行`npm run start`，就好了，可以正常跑页面了，不知道为何。
```json
{
  "presets": [
    "react-app",
    [
      "env",
      {
        "targets": {
          "node": true
        },
        "NODE_ENV":"development",
        "BABEL_ENV":"development"
      }
    ]
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "style": "css"
      }
    ],
    "transform-decorators-legacy"
  ]
}
```

**Comment by mowatermelon** [comment]
或者是我有什么东西没有全局安装，所以导致`package`中的`server`执行语句不成功？

> 我是win7系统

- 先安装的mongo软件
- 配置了`mongo`数据存放和日志地址
- 启动了服务
- 执行了`mongo`连接
- 安装了项目环境依赖包
- 全局安装了`nodemon`
- 然后应该是启动后台服务了吧?

**Comment by KieSun** [comment]
不好意思 我没有 windows 电脑，所以出了问题也不能帮你复现。目前在环境这块出问题的都是 windows，Mac 用户没有和我反正这部分问题。

**Comment by mowatermelon** [comment]
很感谢回答
我回去再用深度试一下

还有  我这边启动服务成功的时候，发现，在商品页面，点击添加按钮一次，默认的是添加了两个，这个是什么原因

![image](https://user-images.githubusercontent.com/18508817/34479084-917e8e62-efdf-11e7-821b-30e0877f9821.png)

**Comment by mowatermelon** [comment]
有点像删除和增加按钮事件会被触发两次，每次添加和删除好像都是这样

**Comment by KieSun** [comment]
@mowatermelon 这个是模拟器 bug，你可以不使用模拟器
