### ISSUE TITLE
讨论：components 中的组件不应该直接访问 redux 和 router

### ISSUE THREAD

**Issue by yuezk** [KieSun/Chat-Buy-React#8]
首先，这是一个很好的项目，但是有个点想和大家讨论一下：

就是 components 的组件应该只和渲染有关，不关心数据和路由。数据和路由应该由 containers 中的组件去做，这个项目中 containers 中的部分组件直接包了一层 components 中的组件就导出了，应该是不太合适的。有些 components 中的组件直接访问了 redux 和 router，感觉也不太合适。

**Comment by KieSun** [comment]
确实有几个做的不妥，稍后我会修改掉。
